export const theme = {
  colors: {
    copper: '#C4956A',
    home: {
      base: '#F7F7F5',
      text: '#2B2A2A',
      forest: '#1B3D2F',
      leather: '#5C3D2E',
      olive: '#4A7A5E',
      hover: '#2D5A3D',
      leadership: '#9AB89E',
      institution: '#9A9590',
      copper: '#C4956A',
    },
    light: {
      background: '#F7F7F5',
      text: '#2B2A2A',
      accent: '#2D5A3D',
      copper: '#C4956A',
      border: '#DBD7D0',
      muted: '#6B6560',
      placeholder: '#ECE8E1',
      cardShadow: 'rgba(37, 32, 27, 0.08)',
    },
    subpage: {
      background: '#F7F7F5',
      text: '#2B2A2A',
      accent: '#2D5A3D',
      copper: '#C4956A',
      border: '#DBD7D0',
      muted: '#6B6560',
      placeholder: '#ECE8E1',
      cardShadow: 'rgba(37, 32, 27, 0.08)',
    },
  },
  fonts: {
    heading: "'Cormorant Garamond', serif",
    body: "'PP Neue Montreal', 'Inter', sans-serif",
  },
  fontSizes: {
    base: '16px',
    h1: '2.5rem',
    h2: '1.8rem',
    h3: '1.3rem',
    body: '1rem',
    small: '0.78rem',
  },
  lineHeights: {
    body: 1.7,
    heading: 1.2,
  },
  spacing: {
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '32px',
    xl: '48px',
    xxl: '64px',
    section: '80px',
    sectionMobile: '48px',
  },
  layout: {
    textMax: '680px',
    pageMax: '900px',
    contentMax: '1100px',
    graphMax: '1100px',
    radius: '4px',
    pillRadius: '4px',
    headerHeight: '88px',
  },
  breakpoints: {
    mobile: '768px',
    tablet: '1024px',
  },
  transitions: {
    hover: 'opacity 0.2s ease, transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease, background 0.2s ease',
    page: { duration: 0.6, ease: 'easeOut' },
  },
};
