export const theme = {
  colors: {
    home: {
      base: '#0D1A14',
      text: '#F5F0E8',
      forest: '#0F3D2E',
      leather: '#5C3D2E',
      olive: '#4A5D3A',
      hover: '#9AB89E',
      leadership: '#8AA27B',
      institution: '#6B746A',
    },
    light: {
      background: '#F5F0E8',
      text: '#2B2A2A',
      accent: '#3D5A3E',
      border: '#D4CFC7',
      muted: '#67615C',
      placeholder: '#E1DBD2',
      cardShadow: 'rgba(37, 32, 27, 0.12)',
    },
    subpage: {
      background: '#F5F0E8',
      text: '#2B2A2A',
      accent: '#3D5A3E',
      border: '#D4CFC7',
      muted: '#67615C',
      placeholder: '#E1DBD2',
      cardShadow: 'rgba(37, 32, 27, 0.12)',
    },
  },
  fonts: {
    heading: "'Cormorant Garamond', serif",
    body: "'PP Neue Montreal', 'Inter', sans-serif",
  },
  fontSizes: {
    base: '16px',
    h1: '2.5rem',
    h2: '1.8rem',
    h3: '1.3rem',
    body: '1rem',
    small: '0.78rem',
  },
  lineHeights: {
    body: 1.7,
    heading: 1.2,
  },
  spacing: {
    xs: '8px',
    sm: '16px',
    md: '24px',
    lg: '32px',
    xl: '48px',
    xxl: '64px',
    section: '80px',
    sectionMobile: '48px',
  },
  layout: {
    textMax: '680px',
    pageMax: '900px',
    contentMax: '1100px',
    graphMax: '1100px',
    radius: '8px',
    pillRadius: '999px',
    headerHeight: '88px',
  },
  breakpoints: {
    mobile: '768px',
    tablet: '1024px',
  },
  transitions: {
    hover: 'opacity 0.2s ease, transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease, background 0.2s ease',
    page: { duration: 0.6, ease: 'easeOut' },
  },
};
